name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Prepare Backend
        run: npm run prepare-backend
      - name: Prepare React
        run: npm run prepare-frontend
      - name: Unit Test Frontend
        run: npm run test-frontend